name: Process Client Files

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
    paths:
      - 'ui_reports/*.html'  # Match files named client_x.json
  workflow_dispatch:

jobs:
  process-client-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract file name
        id: extract_filename
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            FILE=$(git diff --name-only HEAD~1 HEAD | grep -E 'ui_reports/.*\.html')
            if [ -n "$FILE" ]; then
              FILENAME=$(basename $FILE)
              echo "FILE_NAME=${FILENAME}" >> $GITHUB_ENV
            else
              echo "FILE_NAME=" >> $GITHUB_ENV
            fi
          else
            echo "No previous commit found or no JSON files changed in ui_reports."
            echo "FILE_NAME=" >> $GITHUB_ENV
          fi
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python script
        env:
          FILE_NAME: ${{ env.FILE_NAME }}
        run: |
          echo "Processing file: $FILE_NAME"
          python Scraping/ui_scraper.py "$FILE_NAME"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT2 }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add Latest/ui.json
          git commit -m "Add ui report"
          git push origin main 
      - name: Verify commit
        run: |
          echo "Files committed:"
          git show --name-only --oneline HEAD